// <auto-generated />
using System;
using JobCoinAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JobCoinAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("JobCoinAPI.Models.Funcionalidade", b =>
                {
                    b.Property<Guid>("IdFuncionalidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("IdFuncionalidade");

                    b.Property<string>("NomeFuncionalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NomeFuncionalidade");

                    b.HasKey("IdFuncionalidade");

                    b.ToTable("FUNCIONALIDADE");
                });

            modelBuilder.Entity("JobCoinAPI.Models.Perfil", b =>
                {
                    b.Property<Guid>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("IdPerfil");

                    b.Property<string>("NomePerfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NomePerfil");

                    b.HasKey("IdPerfil");

                    b.ToTable("PERFIL");
                });

            modelBuilder.Entity("JobCoinAPI.Models.PerfilFuncionalidade", b =>
                {
                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("IdPerfil");

                    b.Property<Guid>("IdFuncionalidade")
                        .HasColumnType("uuid")
                        .HasColumnName("IdFuncionalidade");

                    b.HasKey("IdPerfil", "IdFuncionalidade");

                    b.HasIndex("IdFuncionalidade");

                    b.ToTable("PERFIL_FUNCIONALIDADE");
                });

            modelBuilder.Entity("JobCoinAPI.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uuid")
                        .HasColumnName("IdPerfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("JobCoinAPI.Models.PerfilFuncionalidade", b =>
                {
                    b.HasOne("JobCoinAPI.Models.Funcionalidade", "Funcionalidade")
                        .WithMany("Perfis")
                        .HasForeignKey("IdFuncionalidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobCoinAPI.Models.Perfil", "Perfil")
                        .WithMany("Funcionalidades")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionalidade");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("JobCoinAPI.Models.Usuario", b =>
                {
                    b.HasOne("JobCoinAPI.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("JobCoinAPI.Models.Funcionalidade", b =>
                {
                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("JobCoinAPI.Models.Perfil", b =>
                {
                    b.Navigation("Funcionalidades");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
